auto: true
url: https://github.com/rancher/fleet.git
chartRepoBranch: charts/v0.11
subdirectory: charts/fleet
workingDir: fleet
additionalCharts:
  - workingDir: fleet-crd
    upstreamOptions:
      url: https://github.com/rancher/fleet.git
      chartRepoBranch: charts/v0.11
      subdirectory: charts/fleet-crd
  - workingDir: fleet-agent
    upstreamOptions:
      url: https://github.com/rancher/fleet.git
      chartRepoBranch: charts/v0.11
      subdirectory: charts/fleet-agent